version: 2.1
executors:
  default:
    docker:
      - image: circleci/node:12.22.1
jobs:
  install-deps:
    executor: default
    steps:
      - checkout
      - restore_cache:
          keys:
            - v{{.Environment.CACHE_VERSION}}-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v{{.Environment.CACHE_VERSION}}-dependencies-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: ./
          paths:
            - node_modules
  lint:
    executor: default
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: yarn lint
  test:
    executor: default
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: yarn test
      - run: curl -s https://codecov.io/bash | bash
  deploy-gh-pages:
    executor: default
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: 
          name: Remove cached version
          command: yarn docs:clean
      - run: 
          name: Copy files to .out
          command: |
            mkdir -p .out
            cp ./README.md .out/README.md
            cp ./_config.yml .out/_config.yml
      - run:
          name: Setup git user
          command: |
            git config user.email "${CIRCLE_USERNAME}@users.noreply.github.com"
            git config user.name "${CIRCLE_USERNAME}"
      - run:
          name: Deploy docs to gh-pages branch
          command: yarn docs:deploy
  release:
    executor: default
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: release
          command: npm run semantic-release
workflows:
  deploy:
    jobs:
      - install-deps
      - lint:
          requires:
            - install-deps
      - test:
          requires:
            - install-deps
      - deploy-gh-pages:
          requires:
            - test
            - lint
          filters:
            branches:
              only: 
                - main
      - release:
          requires:
            - deploy-gh-pages
          filters:
            branches:
              only: main
