version: 2.1
executors:
  default:
    docker:
      - image: circleci/node:12.3.1
jobs:
  install-deps:
    executor: default
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - persist_to_workspace:
          root: ./
          paths:
            - node_modules
  lint:
    executor: default
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: yarn lint
  test:
    executor: default
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: yarn test
      - run: curl -s https://codecov.io/bash | bash
  deploy-gh-pages:
    executor: default
    steps:
      - checkout
      - run: |
          mkdir -p .out
          cp ./README.md .out/README.md
          cp ./_config.yml .out/_config.yml
      - run:
          name: Install and configure dependencies
          command: |
            sudo npm install -g gh-pages@2.0.1
            git config user.email "${CIRCLE_USERNAME}@users.noreply.github.com"
            git config user.name "${CIRCLE_USERNAME}"
      - add_ssh_keys:
          fingerprints:
            - "47:e6:c8:c5:9a:ce:80:14:c2:d8:80:3e:3d:2b:ad:96"
      - run:
          name: Deploy docs to gh-pages branch
          command: |
            gh-pages --message "chore(ci): update documentation [skip ci]" --dist .out
  release:
    executor: default
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run:
          name: release
          command: npm run semantic-release || true
workflows:
  deploy:
    jobs:
      - install-deps
      - lint:
          requires:
            - install-deps
      - test:
          requires:
            - install-deps
      - deploy-gh-pages:
          requires:
            - test
            - lint
          filters:
            branches:
              only: master
      - release:
          requires:
            - deploy-gh-pages
          filters:
            branches:
              only: master
